/* file: msg.c, automatically generated by gencanoe.exe, Version: 5.02 */
/* configuration read from: C:\Users\nituser\AppData\Local\Temp\Cfg_Gen-1707413115827-6\OsProxyFiles-1707418458608-0\Os_ActiveEcuC.arxml.oil */
/* generation at  : Thu Feb 08 19:54:19 2024 */
/* Unlimited license 1234567890 for CANoeEmu Generic License */
/* Implementation: CANoeOsekEmu */
/* Version of general code: 5.31 */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 2
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#include <Os.h>


/* END OF C:\nit-au-03\projekat\AUTOSAR_Exercises\templateAFS\Appl\GenDataVtt\msg.c */

